#!/usr/bin/env python3
import rclpy
from bt_communication.ros2_node import BluetoothROS2Node

def main(args=None):
    rclpy.init(args=args)
    node = BluetoothROS2Node()
    
    # Start the BLE server thread
    node.start_bluetooth_server()
    
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
