# 自動生成: generate_waypoints.py により 2026-03-07 16:57:28 に生成
# 入力: field.pgm (検出壁: north=-0.7020, south=-3.1020, west=-6.8510, east=0.2490)
auto_sequence:
- waypoint_1
- waypoint_2
- waypoint_3
waypoints:
  waypoint_1:
    x: -5.851
    y: -2.602
    theta: 0.0
    on_arrive: []
  waypoint_2:
    x: -5.851
    y: -1.202
    theta: 0.0
    on_arrive: []
  waypoint_3:
    x: -0.751
    y: -2.602
    theta: 0.0
    on_arrive: []
