<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="robot_camera" params="base_height">
    <link name="camera_link">
      <visual><geometry><box size="0.02 0.02 0.02"/></geometry><material name="red"><color rgba="0.8 0.0 0.0 1.0"/></material></visual>
      <collision><geometry><box size="0.02 0.02 0.02"/></geometry></collision>
      <inertial><mass value="0.01"/><inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/></inertial>
    </link>
    <joint name="camera_joint" type="fixed">
      <parent link="base_link"/><child link="camera_link"/><origin xyz="0.2 0.0 ${base_height + 0.15}" rpy="0 0 0"/>
    </joint>
    <gazebo reference="camera_link">
      <sensor name="camera" type="camera">
        <always_on>true</always_on><update_rate>30.0</update_rate>
        <camera><horizontal_fov>1.089</horizontal_fov><image><width>640</width><height>480</height></image></camera>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>
