<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="robot_hand" params="base_link base_length base_width base_height">
    <link name="lift_link">
      <visual><origin xyz="0 0 0.15"/><geometry><box size="0.05 0.2 0.3"/></geometry><material name="grey"><color rgba="0.5 0.5 0.5 1.0"/></material></visual>
      <collision><origin xyz="0 0 0.15"/><geometry><box size="0.05 0.2 0.3"/></geometry></collision>
      <inertial><mass value="1.0"/><inertia ixx="0.01" iyy="0.01" izz="0.01"/></inertial>
    </link>
    <joint name="lift_joint" type="prismatic">
      <parent link="${base_link}"/><child link="lift_link"/><origin xyz="${base_length/2 + 0.025} 0 ${base_height}"/><axis xyz="0 0 1"/><limit lower="0" upper="0.5" effort="100" velocity="0.5"/>
    </joint>
    <link name="gripper_base">
      <visual><geometry><box size="0.1 0.2 0.05"/></geometry></visual>
      <collision><geometry><box size="0.1 0.2 0.05"/></geometry></collision>
      <inertial><mass value="0.2"/><inertia ixx="0.001" iyy="0.001" izz="0.001"/></inertial>
    </link>
    <joint name="gripper_base_joint" type="fixed">
      <parent link="lift_link"/><child link="gripper_base"/><origin xyz="0.05 0 0.3"/>
    </joint>
    <link name="left_finger">
      <visual><origin xyz="0.05 0 0"/><geometry><box size="0.1 0.02 0.05"/></geometry></visual>
      <collision><origin xyz="0.05 0 0"/><geometry><box size="0.1 0.02 0.05"/></geometry></collision>
      <inertial><mass value="0.1"/><inertia ixx="0.0001" iyy="0.0001" izz="0.0001"/></inertial>
    </link>
    <joint name="left_finger_joint" type="revolute">
      <parent link="gripper_base"/><child link="left_finger"/><origin xyz="0.05 0.08 0"/><axis xyz="0 0 1"/><limit lower="-0.5" upper="0.5" effort="10" velocity="1.0"/>
    </joint>
    <link name="right_finger">
      <visual><origin xyz="0.05 0 0"/><geometry><box size="0.1 0.02 0.05"/></geometry></visual>
      <collision><origin xyz="0.05 0 0"/><geometry><box size="0.1 0.02 0.05"/></geometry></collision>
      <inertial><mass value="0.1"/><inertia ixx="0.0001" iyy="0.0001" izz="0.0001"/></inertial>
    </link>
    <joint name="right_finger_joint" type="revolute">
      <parent link="gripper_base"/><child link="right_finger"/><origin xyz="0.05 -0.08 0"/><axis xyz="0 0 1"/><limit lower="-0.5" upper="0.5" effort="10" velocity="1.0"/>
    </joint>
    <gazebo>
      <plugin filename="libignition-gazebo-joint-state-publisher-system.so" name="ignition::gazebo::systems::JointStatePublisher"></plugin>
      <plugin filename="libignition-gazebo-joint-position-controller-system.so" name="ignition::gazebo::systems::JointPositionController">
        <joint_name>lift_joint</joint_name><p_gain>10000</p_gain>
      </plugin>
      <plugin filename="libignition-gazebo-joint-position-controller-system.so" name="ignition::gazebo::systems::JointPositionController">
        <joint_name>left_finger_joint</joint_name><p_gain>100</p_gain>
      </plugin>
      <plugin filename="libignition-gazebo-joint-position-controller-system.so" name="ignition::gazebo::systems::JointPositionController">
        <joint_name>right_finger_joint</joint_name><p_gain>100</p_gain>
      </plugin>
      <plugin filename="libignition-gazebo-pose-publisher-system.so" name="ignition::gazebo::systems::PosePublisher">
        <publish_link_pose>true</publish_link_pose><use_pose_vector_msg>true</use_pose_vector_msg>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>
