<?xml version="1.0"?>
<robot name="khr2026_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find khr2026_team1_simulation)/urdf/mecanum_wheel.xacro"/>
  <xacro:include filename="$(find khr2026_team1_simulation)/urdf/camera.xacro"/>
  <xacro:include filename="$(find khr2026_team1_simulation)/urdf/hand.xacro"/>
  <xacro:property name="wheel_radius" value="0.05"/><xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="base_width" value="0.4"/><xacro:property name="base_length" value="0.5"/><xacro:property name="base_height" value="0.1"/>
  <link name="base_link">
    <visual><origin xyz="0 0 ${base_height/2}"/><geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry><material name="blue"><color rgba="0.0 0.0 0.8 1.0"/></material></visual>
    <collision><origin xyz="0 0 ${base_height/2}"/><geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry></collision>
    <inertial><origin xyz="0 0 ${base_height/2}"/><mass value="10.0"/><inertia ixx="0.1" iyy="0.1" izz="0.1"/></inertial>
  </link>
  <xacro:robot_camera base_height="${base_height}"/>
  <xacro:robot_hand base_link="base_link" base_length="${base_length}" base_width="${base_width}" base_height="${base_height}"/>
  <xacro:mecanum_wheel prefix="front_left" side="1" radius="${wheel_radius}" width="${wheel_width}" x="0.1725" y="0.2425" z="-0.02"/>
  <xacro:mecanum_wheel prefix="front_right" side="-1" radius="${wheel_radius}" width="${wheel_width}" x="0.1725" y="-0.2425" z="-0.02"/>
  <xacro:mecanum_wheel prefix="rear_left" side="1" radius="${wheel_radius}" width="${wheel_width}" x="-0.1725" y="0.2425" z="-0.02"/>
  <xacro:mecanum_wheel prefix="rear_right" side="-1" radius="${wheel_radius}" width="${wheel_width}" x="-0.1725" y="-0.2425" z="-0.02"/>
  <gazebo>
    <plugin filename="libignition-gazebo-mecanum-drive-system.so" name="ignition::gazebo::systems::MecanumDrive">
      <child_frame_id>base_link</child_frame_id>
      <wheel_separation>0.485</wheel_separation><wheelbase>0.345</wheelbase><wheel_radius>${wheel_radius}</wheel_radius>
    </plugin>
  </gazebo>
</robot>
